sudo: false
language: ruby
rvm:
- 2.7.2
before_install:
  - nvm install 12.20.1
  - nvm use 12.20.1
install:
  - bundle install --path vendor/bundle
  - npm install
before_script:
  - chmod +x ./script/cibuild
script: script/cibuild
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
cache:
  - bundler
  - node_modules
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: _site
  on:
    branch: master
