language: ruby
rvm:
- 2.1
before_script:
    - bundle update
    - chmod +x ./script/cibuild
script: script/cibuild

# branch whitelist
branches:
  only:
  - admin # test the admin branch only
  - /admin-(.*)/ # test every branch which starts with "admin-"
