assets:
  digest: true
  compression: true
  source_maps: false
  precompile: [
    avatar-180.jpg,
    avatar-196.jpg,
    avatar-300.jpg
  ]
author: Alex Gibson
domain: https://alxgbsn.co.uk
url: https://alxgbsn.co.uk
exclude:
  - config.rb
  - node_modules
  - script
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - travis.yml
  - vendor
feed:
  path: /feed/index.xml
highlighter: rouge
markdown: kramdown
paginate: 10
paginate_path: 'archive/:num/'
permalink: /:year/:month/:day/:title
plugins:
  - jekyll-assets
  - jekyll-feed
  - jekyll-paginate
rdiscount extensions: [smart]
title: Alex Gibson, Front End Developer
